<a href="https://colab.research.google.com/github/Wuel1/calculonumerico/blob/main/gauss.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import  numpy as np

def gauss(a,b):
    #A é a matriz dos coeficientes
    #B é o vetor de termos independentes

    n = len(b)

    for k in range(0,n-1): #percorre a diagonal
        pivo = a[k][k]

        for i in range(k+1, n): #percorre a linha
            m = a[i][k] / pivo

            for j in range (k,n): #percorre as colunas
                a[i][j] =  a[i][j] - m * a[k][j]

            b[i] = b[i] - m*b[k]
    return a,b

A = [[3,2,4],[1,1,2],[4,3,-2]]
b = [1,2,3]

A_t, b_t =  gauss(A,b)

print("A matriz escalonada é:")
print(np.array(A_t))
print("---------------")
print(b_t)

A matriz escalonada é:
[[ 3.00000000e+00  2.00000000e+00  4.00000000e+00]
 [ 0.00000000e+00  3.33333333e-01  6.66666667e-01]
 [ 0.00000000e+00  5.55111512e-17 -8.00000000e+00]]
---------------
[1, 1.6666666666666667, -4.440892098500626e-16]


In [8]:
def subs_reversa(A_t,b_t):
    n = len(b)
    x = n*[0] #Vetor Solução

    x[n-1] = b[n-1] / A[n-1][n-1]

    for k in range(n-2,-1,-1):
      s = 0
      for j in range(k+1,n):
        s = s +A[k][j]*x[j]


      x[k] = (b[k] - s) / A[k][k]

    return x # retorna a solução do SL A*x = b

    #teste

x = subs_reversa(A_t,b_t)
print("O resultado do sistema Linear é:")
print(x)

O resultado do sistema Linear é:
[-3.0, 5.0, 5.551115123125783e-17]
