<a href="https://colab.research.google.com/github/Wuel1/calculonumerico/blob/main/Hilbert.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import  numpy as np

def gauss(a,b):
    #A é a matriz dos coeficientes
    #B é o vetor de termos independentes

    n = len(b)

    for k in range(0,n-1): #percorre a diagonal
        pivo = a[k][k]

        for i in range(k+1, n): #percorre a linha
            m = a[i][k] / pivo

            for j in range (k,n): #percorre as colunas
                a[i][j] =  a[i][j] - m * a[k][j]

            b[i] = b[i] - m*b[k]
    return a,b

A = [[3,2,4],[1,1,2],[4,3,-2]]
b = [1,2,3]

A_t, b_t =  gauss(A,b)

print("A matriz escalonada é:")
print(np.array(A_t))
print("---------------")
print(b_t)

A matriz escalonada é:
[[ 3.00000000e+00  2.00000000e+00  4.00000000e+00]
 [ 0.00000000e+00  3.33333333e-01  6.66666667e-01]
 [ 0.00000000e+00  5.55111512e-17 -8.00000000e+00]]
---------------
[1, 1.6666666666666667, -4.440892098500626e-16]


In [ ]:
def subs_reversa(A_t,b_t):
    n = len(b)
    x = n*[0] #Vetor Solução

    x[n-1] = b[n-1] / A[n-1][n-1]

    for k in range(n-2,-1,-1):
      s = 0
      for j in range(k+1,n):
        s = s +A[k][j]*x[j]


      x[k] = (b[k] - s) / A[k][k]

    return x # retorna a solução do SL A*x = b

    #teste

x = subs_reversa(A_t,b_t)
print("O resultado do sistema Linear é:")
print(x)

O resultado do sistema Linear é:
[-3.0, 5.0, 5.551115123125783e-17]


Matriz de Hilbert com N = 3

In [61]:
def gauss(a,b):
    #A é a matriz dos coeficientes
    #B é o vetor de termos independentes

    n = len(b)

    for k in range(0,n-1): #percorre a diagonal
        pivo = a[k][k]

        for i in range(k+1, n): #percorre a linha
            m = a[i][k] / pivo

            for j in range (k,n): #percorre as colunas
                a[i][j] =  a[i][j] - m * a[k][j]

            b[i] = b[i] - m*b[k]
    return a,b

def subs_reversa(A_t,b_t):
    n = len(b)
    x = n*[0] #Vetor Solução

    x[n-1] = b[n-1] / A[n-1][n-1]

    for k in range(n-2,-1,-1):
      s = 0
      for j in range(k+1,n):
        s = s +A[k][j]*x[j]


      x[k] = (b[k] - s) / A[k][k]

    return x # retorna a solução do SL A*x = b

def Hilbert(n):
  A = np.zeros((n,n))

  b = n*[0]

  for i in range(0,n):
    for j in range(0,n):
      A[i][j] = 1 / ((i+1) + (j+1) -1)

  for i in range(0,n):
    s = 0
    for j in range(0,n):
      s = s + A[i][j]
    b[i] = s

  return A, b


A, b = Hilbert(3)
A_t,b_t= gauss(A,b);
print(A_t)
print(20*'__')
print(b_t)
print(20*'__')

x = subs_reversa(A_t, b_t)
print(x)


[[ 1.00000000e+00  5.00000000e-01  3.33333333e-01]
 [ 0.00000000e+00  8.33333333e-02  8.33333333e-02]
 [ 0.00000000e+00 -1.38777878e-17  5.55555556e-03]]
________________________________________
[1.8333333333333333, 0.16666666666666663, 0.0055555555555554526]
________________________________________
[0.999999999999998, 1.0000000000000122, 0.9999999999999875]


Matriz de Hilbert com N = 10

In [62]:
def gauss(a,b):
    #A é a matriz dos coeficientes
    #B é o vetor de termos independentes

    n = len(b)

    for k in range(0,n-1): #percorre a diagonal
        pivo = a[k][k]

        for i in range(k+1, n): #percorre a linha
            m = a[i][k] / pivo

            for j in range (k,n): #percorre as colunas
                a[i][j] =  a[i][j] - m * a[k][j]

            b[i] = b[i] - m*b[k]
    return a,b

def subs_reversa(A_t,b_t):
    n = len(b)
    x = n*[0] #Vetor Solução

    x[n-1] = b[n-1] / A[n-1][n-1]

    for k in range(n-2,-1,-1):
      s = 0
      for j in range(k+1,n):
        s = s +A[k][j]*x[j]


      x[k] = (b[k] - s) / A[k][k]

    return x # retorna a solução do SL A*x = b

def Hilbert(n):
  A = np.zeros((n,n))

  b = n*[0]

  for i in range(0,n):
    for j in range(0,n):
      A[i][j] = 1 / ((i+1) + (j+1) -1)

  for i in range(0,n):
    s = 0
    for j in range(0,n):
      s = s + A[i][j]
    b[i] = s

  return A, b


A, b = Hilbert(10)
A_t,b_t= gauss(A,b);
print(A_t)
print(20*'__')
print(b_t)
print(20*'__')

x = subs_reversa(A_t, b_t)
print(x)


[[ 1.00000000e+00  5.00000000e-01  3.33333333e-01  2.50000000e-01
   2.00000000e-01  1.66666667e-01  1.42857143e-01  1.25000000e-01
   1.11111111e-01  1.00000000e-01]
 [ 0.00000000e+00  8.33333333e-02  8.33333333e-02  7.50000000e-02
   6.66666667e-02  5.95238095e-02  5.35714286e-02  4.86111111e-02
   4.44444444e-02  4.09090909e-02]
 [ 0.00000000e+00 -1.38777878e-17  5.55555556e-03  8.33333333e-03
   9.52380952e-03  9.92063492e-03  9.92063492e-03  9.72222222e-03
   9.42760943e-03  9.09090909e-03]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  3.57142857e-04
   7.14285714e-04  9.92063492e-04  1.19047619e-03  1.32575758e-03
   1.41414141e-03  1.46853147e-03]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   2.26757370e-05  5.66893424e-05  9.27643785e-05  1.26262626e-04
   1.55400155e-04  1.79820180e-04]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  1.43154905e-06  4.29464715e-06  8.09375809e-06
   1.23333457e-05  1.66500166e-05

Matriz de Hilbert com N = 100

In [63]:
def gauss(a,b):
    #A é a matriz dos coeficientes
    #B é o vetor de termos independentes

    n = len(b)

    for k in range(0,n-1): #percorre a diagonal
        pivo = a[k][k]

        for i in range(k+1, n): #percorre a linha
            m = a[i][k] / pivo

            for j in range (k,n): #percorre as colunas
                a[i][j] =  a[i][j] - m * a[k][j]

            b[i] = b[i] - m*b[k]
    return a,b

def subs_reversa(A_t,b_t):
    n = len(b)
    x = n*[0] #Vetor Solução

    x[n-1] = b[n-1] / A[n-1][n-1]

    for k in range(n-2,-1,-1):
      s = 0
      for j in range(k+1,n):
        s = s +A[k][j]*x[j]


      x[k] = (b[k] - s) / A[k][k]

    return x # retorna a solução do SL A*x = b

def Hilbert(n):
  A = np.zeros((n,n))

  b = n*[0]

  for i in range(0,n):
    for j in range(0,n):
      A[i][j] = 1 / ((i+1) + (j+1) -1)

  for i in range(0,n):
    s = 0
    for j in range(0,n):
      s = s + A[i][j]
    b[i] = s

  return A, b


A, b = Hilbert(100)
A_t,b_t= gauss(A,b);
print(A_t)
print(20*'__')
print(b_t)
print(20*'__')

x = subs_reversa(A_t, b_t)
print(x)

[[ 1.00000000e+00  5.00000000e-01  3.33333333e-01 ...  1.02040816e-02
   1.01010101e-02  1.00000000e-02]
 [ 0.00000000e+00  8.33333333e-02  8.33333333e-02 ...  4.99896928e-03
   4.94949495e-03  4.90099010e-03]
 [ 0.00000000e+00 -1.38777878e-17  5.55555556e-03 ...  1.59967017e-03
   1.58449178e-03  1.56959814e-03]
 ...
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  4.62813499e-17
   6.74962477e-17  1.00505310e-16]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
   6.64307320e-18  1.13263604e-17]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  1.71363344e-17]]
________________________________________
[5.187377517639621, 1.6035897489188193, 0.3743668411752281, 0.08183241863831447, 0.017289350784816943, 0.003564991801153633, 0.0007201852940913779, 0.00014279034151084505, 2.7808977867119352e-05, 5.322054420119169e-06, 1.0016464019637201e-06, 1.8803182561231787e-07, 4.489657534058364e-08, 1.2059565213777802e-08, 6.5324473