<a href="https://colab.research.google.com/github/Wuel1/calculonumerico/blob/main/gauss.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import  numpy as np

def gauss(a,b):
    #A é a matriz dos coeficientes
    #B é o vetor de termos independentes

    n = len(b)

    for k in range(0,n-1): #percorre a diagonal
        pivo = a[k][k]

        for i in range(k+1, n): #percorre a linha
            m = a[i][k] / pivo

            for j in range (k,n): #percorre as colunas
                a[i][j] =  a[i][j] - m * a[k][j]

            b[i] = b[i] - m*b[k]
    return a,b

A = [[3,2,4],[1,1,2],[4,3,-2]]
b = [1,2,3]

A_t, b_t =  gauss(A,b)

print("A matriz escalonada é:")
print(np.array(A_t))
print("---------------")
print(b_t)

A matriz escalonada é:
[[ 3.00000000e+00  2.00000000e+00  4.00000000e+00]
 [ 0.00000000e+00  3.33333333e-01  6.66666667e-01]
 [ 0.00000000e+00  5.55111512e-17 -8.00000000e+00]]
---------------
[1, 1.6666666666666667, -4.440892098500626e-16]


In [ ]:
def subs_reversa(A_t,b_t):
    n = len(b)
    x = n*[0] #Vetor Solução

    x[n-1] = b[n-1] / A[n-1][n-1]

    for k in range(n-2,-1,-1):
      s = 0
      for j in range(k+1,n):
        s = s +A[k][j]*x[j]


      x[k] = (b[k] - s) / A[k][k]

    return x # retorna a solução do SL A*x = b

    #teste

x = subs_reversa(A_t,b_t)
print("O resultado do sistema Linear é:")
print(x)

O resultado do sistema Linear é:
[-3.0, 5.0, 5.551115123125783e-17]


In [13]:
import  numpy as np

def gauss(a,b):
    #A é a matriz dos coeficientes
    #B é o vetor de termos independentes

    n = len(b)

    for k in range(0,n-1): #percorre a diagonal
        pivo = a[k][k]

        for i in range(k+1, n): #percorre a linha
            m = a[i][k] / pivo

            for j in range (k,n): #percorre as colunas
                a[i][j] =  a[i][j] - m * a[k][j]

            b[i] = b[i] - m*b[k]
    return a,b

A = [[3,2,4],[1,1,2],[4,3,-2]]
b = [1,2,3]

def subs_reversa(A_t,b_t):
    n = len(b)
    x = n*[0] #Vetor Solução

    x[n-1] = b[n-1] / A[n-1][n-1]

    for k in range(n-2,-1,-1):
      s = 0
      for j in range(k+1,n):
        s = s +A[k][j]*x[j]


      x[k] = (b[k] - s) / A[k][k]

    return x # retorna a solução do SL A*x = b

def matriz_de_Hilbert(n):

  A = np.zeros((n,n))

  B = n*[0]

  for i in range(0,n):
    for j in range(0,n):
      A[i][j] = 1 / ((i+1) + (j+1) -1)

  for i in range(0,n):
    s = 0
    for j in range(0,n):
      s = s + A[i][j]
    B[i] = s

  return A, B
  # A é a matriz de Hilbert
  # B é o vetor de termos independentes

A, B = matriz_de_Hilbert(10)
A_t, B_t = gauss(A, B)

print(A_t)
print(20*'__')
print(B_t)
print(20*'__')

x = subs_reversa(A_t, B_t)
print(x)

[[ 1.00000000e+00  5.00000000e-01  3.33333333e-01  2.50000000e-01
   2.00000000e-01  1.66666667e-01  1.42857143e-01  1.25000000e-01
   1.11111111e-01  1.00000000e-01]
 [ 0.00000000e+00  8.33333333e-02  8.33333333e-02  7.50000000e-02
   6.66666667e-02  5.95238095e-02  5.35714286e-02  4.86111111e-02
   4.44444444e-02  4.09090909e-02]
 [ 0.00000000e+00 -1.38777878e-17  5.55555556e-03  8.33333333e-03
   9.52380952e-03  9.92063492e-03  9.92063492e-03  9.72222222e-03
   9.42760943e-03  9.09090909e-03]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  3.57142857e-04
   7.14285714e-04  9.92063492e-04  1.19047619e-03  1.32575758e-03
   1.41414141e-03  1.46853147e-03]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   2.26757370e-05  5.66893424e-05  9.27643785e-05  1.26262626e-04
   1.55400155e-04  1.79820180e-04]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  1.43154905e-06  4.29464715e-06  8.09375809e-06
   1.23333457e-05  1.66500166e-05